### ISSUE TITLE
How to burn firmware without ICSP?

### ISSUE THREAD

**Issue by nehcoab** [wagiminator/ATtiny13-TinyProbe#1]
Hi, Stefan. I noticed that some of your boards using ATTiny don't have an ICSP. How do you usually program them?

**Comment by nehcoab** [comment]
Is there something like a programming socket?

**Comment by wagiminator** [comment]
Hi, since there is no ICSP header on the board (in order to save space), you have to program the ATtiny either before soldering using an [SOP adapter](https://aliexpress.com/wholesale?SearchText=sop-8+150mil+adapter), or after soldering using an [EEPROM clip](https://aliexpress.com/wholesale?SearchText=sop8+eeprom+programming+clip). The [AVR Programmer Adapter](https://github.com/wagiminator/AVR-Programmer/tree/master/AVR_Programmer_Adapter) can help with this.

**Comment by nehcoab** [comment]
As you mentioned, I purchased an SOP8 clip, and the programming was successful. It's now working properly. 
By the way, as a beginner, I have learned and replicated many of your projects, and they are all fantastic. Thanks for your open-source contributions.

**Comment by wagiminator** [comment]
Always welcome !
